name: "keyboard"
description: "Phaser.io Animated keyboard"

source: ./template
destination: ../gh-pages

port: 0xd16a
url: http://keyboard.com

serve:
  - ../gh-pages

marked:
  gfm: true
  tables: true
  breaks: false
  pedantic: false
  sanitize: true
  smartLists: true
  smartypants: false

plugins:
  - huginn-asset-bundler

asset_bundler:
  compress:
    js: true
    css: true
  base_path: /assets/
  shim: /keyboard
  dev: false
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>
"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />
"
